### ISSUE TITLE
Error: Missing "./dist/OfflineIcon.svelte" specifier in "@iconify/svelte" package

### ISSUE THREAD

**Issue by wiseman** [rodneylab/sveltekit-seo#2]
**Describe the bug**
Does not build successfully.

**To Reproduce**

1. Clone the repo.
2. `npm install`
3. `npm run build` (or `npm run dev`).

Gives the following error:

```
[commonjs--resolver] Missing "./dist/OfflineIcon.svelte" specifier in "@iconify/svelte" package
error during build:
Error: Missing "./dist/OfflineIcon.svelte" specifier in "@iconify/svelte" package
    at e (file:///Users/wiseman/src/sveltekit-seo/node_modules/vite/dist/node/chunks/dep-52909643.js:21445:25)
    at n (file:///Users/wiseman/src/sveltekit-seo/node_modules/vite/dist/node/chunks/dep-52909643.js:21445:627)
    at o (file:///Users/wiseman/src/sveltekit-seo/node_modules/vite/dist/node/chunks/dep-52909643.js:21445:1297)
    at resolveExportsOrImports (file:///Users/wiseman/src/sveltekit-seo/node_modules/vite/dist/node/chunks/dep-52909643.js:28746:20)
    at resolveDeepImport (file:///Users/wiseman/src/sveltekit-seo/node_modules/vite/dist/node/chunks/dep-52909643.js:28765:31)
    at tryNodeResolve (file:///Users/wiseman/src/sveltekit-seo/node_modules/vite/dist/node/chunks/dep-52909643.js:28453:20)
    at Object.resolveId (file:///Users/wiseman/src/sveltekit-seo/node_modules/vite/dist/node/chunks/dep-52909643.js:28212:28)
    at Object.handler (file:///Users/wiseman/src/sveltekit-seo/node_modules/vite/dist/node/chunks/dep-52909643.js:48308:19)
    at file:///Users/wiseman/src/sveltekit-seo/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/wiseman/src/sveltekit-seo/node_modules/rollup/dist/es/shared/node-entry.js:25444:28)
```

**Desktop (please complete the following information):**

- macOS

**Comment by rodneylab** [comment]
@wiseman 
Thanks John, sorry for the late reply.  Just wanted to let you know that I have just updated everything, so this issue should have been remedied.  Do let me know though!
